version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html/php
      - ./js:/var/www/html/js
      - ./css:/var/www/html/css
      - ./assets:/var/www/html/assets
      - ./index.html:/var/www/html/index.html
      - ./login.html:/var/www/html/login.html
      - ./register.html:/var/www/html/register.html
      - ./profile.html:/var/www/html/profile.html
    depends_on:
      - mysql
      - redis
      - mongo
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MYSQL_USER=guviuser
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=guvi
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: guvi
      MYSQL_USER: guviuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  redis_data:
  mongo_data: